const PC_ASSIGNMENTS = {
  term1: null, // no data yet
  term2: null, // no data yet
  term3: {
    "3A": [
      { name: "ANDRADE RODRIGUEZ SILVANA", pc: 4 },
      { name: "BUITRAGO MÉNDEZ JUAN ANDRÉS", pc: 14 },
      { name: "CABRERA BARRERO JULIETA", pc: 23 },
      { name: "CAMACHO SALAZAR JULIANA", pc: 3 },
      { name: "CAMERO PERDOMO JOSÉ MIGUEL", pc: 9 },
      { name: "CASTAÑEDA RENGIFO ISABELLA", pc: 26 },
      { name: "CHACÓN RAMÍREZ THOMAS", pc: 12 },
      { name: "CORTES LOSADA ARIADNA VALENTINA", pc: 11 },
      { name: "GOMEZ GONZALEZ AARON", pc: 17 },
      { name: "GRANJA PABÓN THIAGO", pc: 7 },
      { name: "GUEVARA ORTIZ JUAN ÁLVARO", pc: 2 },
      { name: "HERNANDEZ CELEITA MARIA ANTONIA", pc: 5 },
      { name: "MACIAS IBÁÑEZ SAMUEL ANDRÉS", pc: 6 },
      { name: "MOGOLLÓN RODRÍGUEZ MELISSA", pc: 13 },
      { name: "NIÑO GALINDO SAMANTHA VICTORIA", pc: 8 },
      { name: "PATIÑO CLAROS GABRIELA", pc: 16 },
      { name: "RAMOS MORA VALENTINA ESTRELLITA", pc: 10 },
      { name: "RIVERA HERRERA MAYTE", pc: 20 },
      { name: "RUGELES CASTAÑEDA DYLAN THOMAS", pc: 21 },
      { name: "SAAVEDRA OYOLA EIDER IVAN", pc: 19 },
      { name: "SÁNCHEZ LUCUARA CELESTE", pc: 15 },
      { name: "SERRATO MORENO EMILIANO", pc: 25 },
      { name: "TAMAYO CASTAÑEDA SAMUEL", pc: 18 },
      { name: "TORRES SARRIA ANTONELLA", pc: 1 },
      { name: "VÁSQUEZ PEREZ EMILIANO", pc: 22 },
      { name: "YASNO ÁVILA MATIAS", pc: 24 },
    ],
    "3B": [
      { name: "ARIAS MAJE GABRIEL MATIAS", pc: 6 },
      { name: "BALLESTEROS COLLAZOS CRISTOBAL", pc: 1 },
      { name: "BORRERO CORREA ANNIE DANIELA", pc: 12 },
      { name: "CALDERÓN MORALES EMILIANO", pc: 13 },
      { name: "CASAS BUITRAGO CELESTE SOFIA", pc: 8 },
      { name: "CELORIO OVIEDO KILIAN ANDREI", pc: 25 },
      { name: "CRÍALES MORENO JULIETA", pc: 3 },
      { name: "DIAZ MEJÍA RONNY ESTIVEN", pc: 9 },
      { name: "GAITAN VELASQUEZ GABRIELLA", pc: 20 },
      { name: "GONZALEZ SUAREZ ANA MARIA", pc: 7 },
      { name: "GRANJA PABÓN IVANNA", pc: 23 },
      { name: "IBAGON RANGEL EMILY", pc: 17 },
      { name: "JIMÉNEZ ZAMBRANO FEDERICK", pc: 22 },
      { name: "MARIN ORDOÑEZ SARA VICTORIA", pc: 5 },
      { name: "MORA MURCIA JULIÁN FELIPE", pc: 19 },
      { name: "ORDOÑEZ GUTIÉRREZ MARTIN", pc: 24 },
      { name: "PATIÑO MARTÍNEZ EDINSON", pc: 10 },
      { name: "POLANIA BASTIDAS DYLAN SANTIAGO", pc: 4 },
      { name: "PUENTES DIAZ LUIS ESTEBAN", pc: 16 },
      { name: "PUENTES REYES EMMANUEL", pc: 18 },
      { name: "SABI MONJE ANTONELLA", pc: 26 },
      { name: "SALAZAR DIAZ ANNY MILAGROS", pc: 14 },
      { name: "SANCHEZ OSPITIA LUCIANA", pc: 11 },
      { name: "SIERRA MEDINA MATHIAS", pc: 15 },
      { name: "VARGAS RODRIGUEZ MARIANA", pc: 21 },
      { name: "VARGAS TRUJILLO EMMANUEL", pc: 2 },
    ],
    "3C": [
      { name: "ACOSTA PARRA SALOMÓN", pc: 12 },
      { name: "ÁVILA ORTEGA GABRIELA", pc: 21 },
      { name: "AVILÉS DUSSÁN MATHIAS", pc: 20 },
      { name: "BARRERO GÓMEZ SANTIAGO", pc: 3 },
      { name: "BARRETO RAMIREZ NHARA ISABELA", pc: 8 },
      { name: "BASTOS CÁRDENAS SIMÓN", pc: 4 },
      { name: "BUITRAGO JAVELA EMMA", pc: 1 },
      { name: "CALLEJAS SOSA EMILIA", pc: 19 },
      { name: "CASTILLO ROJAS GABRIELA", pc: 11 },
      { name: "DIAZ CARVAJAL ARTURO", pc: 13 },
      { name: "FRANCO DÍAZ ALAN JERÓNIMO", pc: null },
      { name: "JIMÉNEZ BOHADA EMILIANO", pc: 17 },
      { name: "MEJÍA BORRERO MARIANA", pc: 9 },
      { name: "MORALES FARFÁN MARTINA", pc: 18 },
      { name: "OSORIO RUIZ JUAN ANDRÉS", pc: 6 },
      { name: "ROBLEDO SANTANA SALOME", pc: 16 },
      { name: "RODRIGUEZ ALVAREZ MARTIN ANDRES", pc: 5 },
      { name: "ROJAS CLAROS SELENE", pc: 14 },
      { name: "ROJAS SANDOVAL AVRIL CATALINA", pc: 22 },
      { name: "SANCHEZ HERNANDEZ ISAAC", pc: 24 },
      { name: "SANCHEZ LOPEZ DYLAN ARMANDO", pc: 23 },
      { name: "SILVA BAHAMÓN MANUEL FELIPE", pc: 10 },
      { name: "SOTELO BRAVO JUAN JOSE", pc: 7 },
      { name: "TOVAR VARGAS GABRIELA", pc: 15 },
      { name: "TRIVIÑO GARCÍA YULIANY", pc: 2 },
    ],
    "4A": [
      { name: "ALMARIO URREGO JERONIMO", pc: 15 },
      { name: "ARISTIZABAL ALVARADO ISABELLA", pc: 3 },
      { name: "ASTAIZA MONTEALEGRE SALOMÉ", pc: 23 },
      { name: "BLANCO VANEGAS SAMUEL", pc: 16 },
      { name: "CALDERÓN RINCÓN SARA", pc: 28 },
      { name: "CAMAYO CABRERA JUAN ALVARO", pc: 9 },
      { name: "CARDENAS MONTES SAMUEL", pc: 10 },
      { name: "CENDALES QUEVEDO JEREMY EITHAN", pc: 26 },
      { name: "CUELLAR AMAYA MILAN", pc: 17 },
      { name: "CUELLAR JAVELA JUAN MARTIN", pc: 21 },
      { name: "DURAN SANCHEZ SALOMÉ", pc: 6 },
      { name: "FONSECA PEÑA LUCIANA", pc: 25 },
      { name: "GONZALEZ CORAL NICOLAS", pc: 19 },
      { name: "GURTIERREZ REYES MANUELA", pc: 5 },
      { name: "JOAQUI CARDOZO WILLIAM SANTIAGO", pc: 12 },
      { name: "LEÓN NIÑO SARA MARIA", pc: 13 },
      { name: "LEYVA GONZALEZ ANA LUCÍA", pc: 8 },
      { name: "LOPEZ ANDRADE SALOME", pc: 7 },
      { name: "MUÑOZ RAMON MATHIAS", pc: 27 },
      { name: "MURCIA ASENCIO SANTIAGO", pc: 4 },
      { name: "OÑATE SALAMANCA LUCIA", pc: 1 },
      { name: "ORTIZ CHAVARRO THOMAS FELIPE", pc: 11 },
      { name: "PEREZ TRUJILLO ALAN MATHIAS", pc: 22 },
      { name: "PINILLA JIMENEZ SARA VICTORIA", pc: 24 },
      { name: "REYEZ PEREZ MATHIAS", pc: 20 },
      { name: "RICARDO CUTA ELIZABETH", pc: 14 },
      { name: "RUBIANO YARA TOMÁS", pc: 2 },
      { name: "POLO MURCIA DAVID SANTIAGO", pc: 29 },
      { name: "SANCHEZ DÍAZ JAIRO ANDRES", pc: 18 },
    ],
    "4B": [
      { name: "ALARCON SABOGAL ANA LUCIA", pc: 15 },
      { name: "BARRIOS GALINDO SAMUEL", pc: 29 },
      { name: "BONILLA QUINTERO VALENTINA", pc: 18 },
      { name: "CALDERON FONSECA JULIANA", pc: 17 },
      { name: "FANDIÑO CORTES VICTORIA", pc: 6 },
      { name: "FIERRO QUINTERO ANA SOFÍA", pc: 24 },
      { name: "FIGUEROA MORENO RAFAEL SANTIAGO", pc: 10 },
      { name: "GUERRERO MUÑOZ ANGEL GABRIEL", pc: 2 },
      { name: "JAVELA PLAZAS SAMUEL ANDRES", pc: 13 },
      { name: "MADRID BONILLA EMANUEL", pc: 21 },
      { name: "MORA QUIMBAYA THIAGO JULIAN", pc: 12 },
      { name: "MORENO MONJE TOMAS", pc: 3 },
      { name: "MOSQUERA ROJAS SALOMÉ", pc: 16 },
      { name: "MUNAR MOSQUERA JERONIMO", pc: 4 },
      { name: "MURCIA OCAMPO TOMAS", pc: 24 },
      { name: "OLAYA IZQUIERDO PALOMA", pc: 11 },
      { name: "ORTIZ MOLANO GABRIELA", pc: 19 },
      { name: "PACHECO GAMBOA LUCIANA", pc: 7 },
      { name: "PARDO VARON EMMANUEL", pc: 22 },
      { name: "PERDOMO CÓRDOBA JUAN ESTEBAN", pc: 9 },
      { name: "QUESADA RODRIGUEZ ANTONELLA", pc: 8 },
      { name: "RIVERA MUÑOZ ABRIL", pc: 20 },
      { name: "RIVERA ROJAS LUCIANA", pc: 23 },
      { name: "ROA RAMIREZ ANA SOFÍA", pc: 28 },
      { name: "SASTOQUE VILLARREAL JOSÉ DAVID", pc: 14 },
      { name: "TRILLERAS RINCON JUAN PABLO", pc: 27 },
      { name: "TRUJILLO RIVERA ANA VICTORIA", pc: 5 },
      { name: "URRIAGO ANDRADE CELESTE", pc: 1 },
      { name: "VASQUEZ RAMIREZ SANTIAGO", pc: 26 },
    ],
    "4C": [
      { name: "ALEGRÍA PLAZAS PABLO JOSÉ", pc: 2 },
      { name: "BERNAL MOTTA LAURA VALENTINA", pc: 5 },
      { name: "CABRERA MENDEZ ANAMARIA", pc: 10 },
      { name: "CARRILLO GOMEZ ALEJANDRO", pc: 9 },
      { name: "CASTRO LEYTON BRIANA ALETH", pc: 15 },
      { name: "CELORIO OVIEDO KESHIA CAROLINA", pc: 11 },
      { name: "CERQUERA MONTEALEGRE TOMAS", pc: 12 },
      { name: "CÉSPEDES CORTES SAMANTHA", pc: 1 },
      { name: "FIERRO JOVEN MATIAS", pc: 16 },
      { name: "GUTIERREZ HUELGO SAMUEL", pc: 4 },
      { name: "HERNANDEZ DUSSAN MIA", pc: 24 },
      { name: "HUERTAS JAIMES ALEJANDRA", pc: 6 },
      { name: "LUNA CALDERON JUANA VICTORIA", pc: 20 },
      { name: "MOTTA BERNATE LUCIANO", pc: 29 },
      { name: "OTALORA BARBOSA SANTIAGO ANDRÉS", pc: 21 },
      { name: "PATIÑO RICO DANIEL", pc: 18 },
      { name: "PENNA LAISECA ANTONELLA", pc: 17 },
      { name: "PEÑA OSORIO VALERIA", pc: 7 },
      { name: "PEREZ LOPEZ EVA MARIA", pc: 14 },
      { name: "RODRIGUEZ SARRIAS JUAN JOSÉ", pc: 23 },
      { name: "PORTILLA BENITEZ DANNA", pc: 28 },
      { name: "QUIROZ GARCIA EMILIANO", pc: 30 },
      { name: "RAMOS VARGAS LORENZO", pc: 27 },
      { name: "RENDON CUELLAR EMILIO", pc: 13 },
      { name: "RIOS SERRATO JUAN JOSÉ", pc: 3 },
      { name: "SANDOVAL SANCHEZ LAURA", pc: 8 },
      { name: "TAMAYO TORRES EMILIANO", pc: 22 },
      { name: "VANEGAS TORRES SARA LUCÍA", pc: 26 },
      { name: "VICTORIA HERNANDEZ PAULA ANDREA", pc: 25 },
      { name: "VIEDA DIAZ ERMES SANTIAGO", pc: 19 },
    ],
    "5A": [
      { name: "ARISTIZABAL RINCÓN MARÍA JOSÉ", pc: 3 },
      { name: "ARTUNDUAGA PASTRANA MARIANA", pc: 13 },
      { name: "BARREIRO GARCÍA SANTIAGO", pc: 11 },
      { name: "BARRETO DUSSAN MARTÍN", pc: 26 },
      { name: "BONILLA QUIROGA ANA SOFIA", pc: 21 },
      { name: "BONILLA RAMIREZ JHON FREDY", pc: 19 },
      { name: "CAMACHO SALAZAR THALIANA", pc: 23 },
      { name: "CARDENAS TOVAR DANIEL MATHIAS", pc: 25 },
      { name: "CEDEÑO CEDEÑO ISABELLA", pc: 6 },
      { name: "CUELLAR CELIS EMILIANO", pc: 12 },
      { name: "DÍAZ MEJÍA MARÍA CELESTE", pc: 27 },
      { name: "DÍAZ RODRIGUEZ CELESTE", pc: 10 },
      { name: "DUSSÁN ROJAS ORALIS ARIANA", pc: 5 },
      { name: "GONZÁLEZ FERNÁNDEZ ÁNGEL GABRIEL", pc: 24 },
      { name: "GONZALEZ SUAREZ LUCIANA CELESTE", pc: 9 },
      { name: "HERNÁNDEZ ZEA SAMUEL", pc: 4 },
      { name: "HUESO HERNANDEZ JOSE ALEJANDRO", pc: 2 },
      { name: "LUGO SILVA DALIANA LUCIA", pc: 8 },
      { name: "PERDOMO HERRERA SAMUEL", pc: 18 },
      { name: "PERLAZA MEDINA SAMUEL JOSÉ", pc: 7 },
      { name: "PINZÓN NÁRVAEZ SARA VALENTINA", pc: 20 },
      { name: "POLANCO VEGA EMMANUEL", pc: 14 },
      { name: "SANCHEZ DONATO THALYA", pc: 16 },
      { name: "SILVA CABRERA JOSÉ DAVID", pc: 1 },
      { name: "TELLO PERÉZ GUADALUPE", pc: 15 },
      { name: "URREA VANEGAS SANTIAGO", pc: 28 },
      { name: "VARGAS TRUJILLO SIMON ALFREDO", pc: 22 },
      { name: "VARGAS VASQUEZ DYLAN SAMUEL", pc: 17 },
    ],
    "5B": [
      { name: "ACERO SOTO DANNA SOFIA", pc: 8 },
      { name: "AGUIRRE POLANIA MARTHA LUCIA", pc: 12 },
      { name: "AGUIRRE SANTOFIMIO GABRIELA", pc: 6 },
      { name: "ANDRADE TAMAYO ANA ISABEL", pc: 15 },
      { name: "AREVALO GONZALEZ ANGELA MARÍA", pc: 7 },
      { name: "CHACÓN RUJANA ZAHIRA SOFÍA", pc: 11 },
      { name: "CLAROS AGUDELO ARIADNA CLAROS", pc: 13 },
      { name: "ESPINOSA BUSTACARA ANA ISABELLA", pc: 3 },
      { name: "ESQUIVEL MOSQUERA ANTONELLA", pc: 21 },
      { name: "GUIO QUINTERO JUAN PABLO", pc: 2 },
      { name: "HERNANDEZ PINEDA JULIAN DAVID", pc: 17 },
      { name: "MEJÍA BORRERO JUAN ESTEBAN", pc: 28 },
      { name: "MONJE ORDOÑEZ MARÍA VICTORIA", pc: 9 },
      { name: "MOSQUERA BAYLÓN KEVIN SAMUEL", pc: 24 },
      { name: "OBREGÓN SÁNCHEZ JUAN MARTÍN", pc: 23 },
      { name: "ORTEGA CORTÉS NICOLL MARIANA", pc: 27 },
      { name: "ORTIZ GONZÁLEZ RAFAEL THOMAS", pc: 5 },
      { name: "PALACIOS SANCHÉZ MARÍA ANTONIA", pc: 4 },
      { name: "PARRA VITOVIZ NICOLAS MAURICIO", pc: 16 },
      { name: "PERDOMO GRAFFE LUCIANA", pc: 22 },
      { name: "PINCHAO VALENZUELA MARTÍN", pc: 19 },
      { name: "ROJAS PAYAN GABRIEL DAVID", pc: 10 },
      { name: "SORA ORTIZ JERÓNIMO", pc: 14 },
      { name: "TOVAR BAHAMÓN SAMUEL DAVID", pc: 18 },
      { name: "TRUJILLO TORREJANO LENIN SANTIAGO", pc: 20 },
      { name: "VERGARA MOLANO JUAN FELIPE", pc: 26 },
      { name: "VILLARREAL BASTIDAS IANN SANTIAGO", pc: 25 },
      { name: "ZORRO FERNÁNDEZ SALOMÉ", pc: 1 },
    ],
    "5C": [
      { name: "CABREJO GONZÁLEZ SAMUEL", pc: null },
      { name: "CARDENAS RODRIGUEZ EDUARD SANTIAGO", pc: null },
      { name: "CHINCHILLA RÍOS VIOLETTA", pc: null },
      { name: "CLAVIJO PERDOMO EMMA", pc: null },
      { name: "CORREDOR AROCA MATÍAS", pc: null },
      { name: "CUBILLOS CAMACHO VALERIA", pc: null },
      { name: "DÍAZ SONS ANGEL MARTÍN", pc: null },
      { name: "DUSSAN LEMUS JULIETA", pc: null },
      { name: "GAITÁN VARGAS ANA LUCÍA", pc: null },
      { name: "ICOPO MELENDEZ LUCAS ANDRÉS", pc: null },
      { name: "JARA ALDANA MARTÍN", pc: null },
      { name: "MEDINA OBANDO DAVID ESTEBAN", pc: null },
      { name: "MOLINA LOZADA SAMANTHA", pc: null },
      { name: "ORTIGOZA GÓMEZ MIA SALOMÉ", pc: null },
      { name: "PACHECO PEREZ GABRIEL ALEJANDRO", pc: null },
      { name: "PALOMINO HERNÁNDEZ MARTÍN", pc: null },
      { name: "PÉREZ NIÑO ABRIL", pc: null },
      { name: "PINEDA UNÍ EMMANUEL", pc: null },
      { name: "PRECIADO CUERVO ISABELLA", pc: null },
      { name: "PUENTES SUAREZ GINA MARCELA", pc: null },
      { name: "RAMÍREZ SALCEDO JUAN ANDRÉS", pc: null },
      { name: "RAMIREZ YEPES LUCIA", pc: null },
      { name: "RENGIFO OTALORA JUANA VALERIA", pc: null },
      { name: "RINCÓN MEDINA SAMUEL NICOLÁS", pc: null },
      { name: "ROMERO TAMAYO EMILY LUCIANA", pc: null },
      { name: "VALENCIA PACHECO JORGE MARÍO", pc: null },
      { name: "VELEZ GOMEZ MIGUEL ANGEL", pc: null },
      { name: "ZAPATA SALAZAR JUAN ANDRÉS", pc: null },
    ],
    "5D": [
      { name: "ALMARIO GAMBOA DANTE", pc: null },
      { name: "ALVARADO GÓMEZ JERÓNIMO", pc: null },
      { name: "ALVIRA CHARRY JUAN SEBASTIÁN", pc: null },
      { name: "ÁNGEL PERDOMO THIAGO EMMANUEL", pc: null },
      { name: "CAMACHO GARCÍA DIEGO ANDRÉS", pc: null },
      { name: "CARVAJAL PLAZA LUCIANA", pc: null },
      { name: "CONTRERAS GARCÍA ANALUCIA", pc: null },
      { name: "CORTES TRUJILLO JERONIMO", pc: null },
      { name: "DÍAZ POLANIA GABRIELA", pc: null },
      { name: "FAJARDO CASTAÑEDA MARÍA PAZ", pc: null },
      { name: "FORTALECHE POLANIA SARA DAILY", pc: null },
      { name: "GUTIERREZ DUSSÁN SARA VALENTINA", pc: null },
      { name: "HERRERA LEÓN AMÉRICA ISABELA", pc: null },
      { name: "MAYOR MOTTA JERÓNIMO", pc: null },
      { name: "MENESES TEJADA JULIETA MARÍA", pc: null },
      { name: "ORDOÑEZ GÓMEZ JUAN JOSÉ", pc: null },
      { name: "OYOLA CUTIVA JOSE ALEJANDRO", pc: null },
      { name: "PERALTA MEDINA SALOME", pc: null },
      { name: "PINO ALARCÓN SANTIAGO", pc: null },
      { name: "PUENTES DÍAZ ADRIAN FELIPE", pc: null },
      { name: "PULIDO LOSADA JUAN JOSE", pc: null },
      { name: "RIVERA DÍAZ ANA SOFIA", pc: null },
      { name: "RUBIANO ORTIZ DANTE", pc: null },
      { name: "SÁNCHEZ HERNÁNDEZ SALOMÉ", pc: null },
      { name: "SUAZA FAJARDO ISABELLA", pc: null },
      { name: "TAMAYO ALVARADO EMILIANO", pc: null },
      { name: "TRUJILLO MONTEALEGRE ISABELLA", pc: null },
      { name: "VARGAS ZAPATA ADRIAN EDUARDO", pc: null },
    ],
  },
  term4: null, // to be added later
};
